# Generated by Django 3.2.23 on 2024-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
    ]
