# Generated by Django 3.2.23 on 2024-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quiz_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Title'),
        ),
    ]
